import SwiftUI
import SwiftData

struct ClinicalExamView: View {
    let patient: PatientProfile
    @Environment(\.modelContext) private var modelContext
    @StateObject private var intelligenceService = ClinicalIntelligenceService()

    @State private var selectedAnatomy: String? = nil
    @State private var dictationText: String = "Found a 2mm basal cell carcinoma here. Patient states it has been bleeding for two weeks."
    @State private var isProcessing = false
    @State private var generatedNote: ClinicalVisitNote?
    @State private var generatedPDFURL: URL?

    var body: some View {
        VStack(spacing: 0) {
            // Liquid Glass Top Navigation Wrapper (iPad Section 3.4)
            iPadClinicalToolbar()
                .padding(.top, 10)
                .padding(.bottom, 10)
                .zIndex(1)

            HStack(spacing: 0) {
                // Section 4: 3D Anatomical Atlas (Left side)
                ZStack {
                    #if os(macOS)
                    Color(NSColor.windowBackgroundColor)
                    #else
                    Color(UIColor.systemBackground)
                    #endif

                    AnatomicalRealityView(selectedAnatomy: $selectedAnatomy)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .clipShape(RoundedRectangle(cornerRadius: 16))
                .padding()

                // Section 5.1: Clinical AI Integration (Right side)
                VStack(alignment: .leading, spacing: 20) {
                    Text("Clinical Intelligence")
                        .font(.title2)
                        .bold()
                        .foregroundColor(.purple)

                    if let part = selectedAnatomy {
                        HStack {
                            Image(systemName: "viewfinder")
                            Text("Spatial Focus: \(part)")
                        }
                        .font(.subheadline)
                        .padding(8)
                        .background(.purple.opacity(0.1))
                        .cornerRadius(8)
                    }

                    VStack(alignment: .leading, spacing: 8) {
                        Text("Dictation").font(.headline)
                        #if os(iOS)
                        TextEditor(text: $dictationText)
                            .frame(height: 120)
                            .padding(4)
                            .background(Color(UIColor.secondarySystemBackground))
                            .cornerRadius(8)
                        #else
                        TextEditor(text: $dictationText)
                            .frame(height: 120)
                            .padding(4)
                            .background(Color(NSColor.controlBackgroundColor))
                            .cornerRadius(8)
                        #endif
                    }

                    Button(action: runAIWorkflow) {
                        HStack {
                            if isProcessing {
                                ProgressView()
                                    .padding(.trailing, 4)
                            } else {
                                Image(systemName: "waveform.circle.fill")
                            }
                            Text(isProcessing ? "Processing via Local ~3B Model..." : "Process Diagnostics")
                        }
                        .frame(maxWidth: .infinity)
                        .padding()
                        #if os(iOS)
                        .foregroundColor(.white)
                        .background(Color.purple)
                        #else
                        .background(Color.purple)
                        #endif
                        .cornerRadius(12)
                    }
                    .disabled(isProcessing)

                    Divider()

                    // Display Section 2.2: Structured Output
                    if let note = generatedNote {
                        ScrollView {
                            VStack(alignment: .leading, spacing: 12) {
                                Text("Structured Output generated by FoundationModels")
                                    .font(.caption)
                                    .foregroundColor(.gray)

                                clinicalDataRow(title: "CC/HPI", value: note.ccHPI)
                                clinicalDataRow(title: "Exam", value: note.examFindings)
                                clinicalDataRow(title: "Plan", value: note.impressionsAndPlan)
                            }
                        }
                        .frame(maxHeight: 250)

                        // Section 5.2: Generate PDF
                        Button(action: {
                            generateAndSaveDocument(note: note)
                        }) {
                            Label("Sign & Generate PDF", systemImage: "signature")
                                .frame(maxWidth: .infinity)
                                .padding()
                                #if os(iOS)
                                .foregroundColor(.white)
                                .background(Color.blue)
                                #else
                                .background(Color.blue)
                                #endif
                                .cornerRadius(12)
                        }
                    }

                    if let url = generatedPDFURL {
                        HStack {
                            Image(systemName: "checkmark.seal.fill")
                                .foregroundColor(.green)
                            Text("Stored locally: \(url.lastPathComponent)")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                        }
                    }

                    Spacer()
                }
                .padding()
                .frame(width: 400)
                #if os(iOS)
                .background(Color(UIColor.secondarySystemBackground))
                #else
                .background(Color(NSColor.windowBackgroundColor))
                #endif
            }
        }
        .navigationTitle("Exam Space")
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
    }

    private func runAIWorkflow() {
        isProcessing = true
        var contextualDictation = dictationText
        if let part = selectedAnatomy {
            contextualDictation = "[Anatomical Focus: \(part)] " + contextualDictation
        }

        Task {
            do {
                let note = try await intelligenceService.generateStructuredNote(from: contextualDictation)
                await MainActor.run {
                    self.generatedNote = note
                    self.isProcessing = false
                }
            } catch {
                print("Inference error: \(error)")
                await MainActor.run { self.isProcessing = false }
            }
        }
    }

    private func generateAndSaveDocument(note: ClinicalVisitNote) {
        let record = LocalClinicalRecord(
            recordID: UUID().uuidString,
            dateRecorded: Date(),
            conditionName: note.impressionsAndPlan,
            status: "Final",
            isHiddenFromPortal: false
        )
        modelContext.insert(record)
        // Note: Assuming patient.clinicalRecords is an optional array as defined:
        patient.clinicalRecords?.append(record)
        try? modelContext.save()

        if let url = generatePDFLocally(patient: patient, record: record, details: note) {
            generatedPDFURL = url
        }
    }

    private func clinicalDataRow(title: String, value: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(title).font(.caption).bold().foregroundColor(.secondary)
            Text(value).font(.body)
        }
    }
}
